tools:
  ClangFormat:
    enable: True
    exclude:
      match:
      - ext/.*
      - src/language/templates/*
      - test/usecases/*/*
  ClangTidy:
    enable: true
    option: ''
    exclude:
      match:
      - src/language/templates/*
  CMakeFormat:
    enable: True
    exclude:
      match:
      - ext/.*
      - src/language/templates/*
