cache: &global_cache
  key: ${CI_COMMIT_REF_SLUG}
  paths:
  - venv/
  - build_gcc/
  - build_intel/
  - build_llvm/

setup virtualenv:
  stage: .pre
  tags: [bb5]
  script:
  - export
  - ci/bb5-pr
  only:
  - external_pull_requests

build intel:
  stage: build
  tags: [bb5]
  script: ci/bb5-pr
  resource_group: build
  only:
  - external_pull_requests

test intel: &test_config
  stage: test
  tags: [bb5]
  script: ci/bb5-pr
  resource_group: test
  dependencies:
  - build intel
  only:
  - external_pull_requests
  cache:
    <<: *global_cache
    policy: pull

cmake format: *test_config
clang format: *test_config
