stages:
  - .pre
  - build
  - linters
  - test

.common:
  tags: [bb5]
  script: ci/bb5-pr.sh
  only:
    - external_pull_requests
  variables:
    # Just run everything in the same, persistent, directory.
    bb5_build_dir: pipeline

setup virtualenv:
  extends: .common
  stage: .pre
  before_script:
    - export

build intel:
  extends: .common
  stage: build
  resource_group: build
  variables:
    # We cloned in .pre
    GIT_STRATEGY: none

test intel:
  extends: .common
  stage: test
  resource_group: test
  variables:
    # We cloned in .pre
    GIT_STRATEGY: none

build pgi:
  extends: .common
  stage: build
  resource_group: build
  variables:
    # We cloned in .pre
    GIT_STRATEGY: none
    bb5_constraint: volta

test pgi:
  extends: .common
  stage: test
  resource_group: test
  variables:
    # We cloned in .pre
    GIT_STRATEGY: none

cmake format:
  extends: .common
  stage: linters
  resource_group: linters
  variables:
    # We cloned in .pre
    GIT_STRATEGY: none

clang format:
  extends: .common
  stage: linters
  resource_group: linters
  variables:
    # We cloned in .pre
    GIT_STRATEGY: none
