.common:
  tags: [bb5]
  script: ci/bb5-pr.sh
  only:
    - external_pull_requests
  variables:
    # Just run everything in the same, persistent, directory.
    bb5_build_dir: pipeline

setup virtualenv:
  extends: .common
  stage: .pre
  before_script:
    - export

build intel:
  extends: .common
  stage: build
  resource_group: build
  variables:
    # We cloned in .pre
    GIT_STRATEGY: none

test intel: &test_config
  extends: .common
  stage: test
  resource_group: test
  variables:
    # We cloned in .pre
    GIT_STRATEGY: none

build pgi:
  tags: bb5
  script: ci/bb5-pr.sh
  only:
    - external_pull_requests
  stage: build
  resource_group: build
  variables:
    # We cloned in .pre
    GIT_STRATEGY: none
    bb5_constraint: volta

# test pgi: &test_config
#   extends: .common
#   stage: test
#   resource_group: test
#   variables:
#     # We cloned in .pre
#     GIT_STRATEGY: none

cmake format: *test_config
clang format: *test_config
