include:
  - project: hpc/gitlab-pipelines
    file: github-project-pipelines.gitlab-ci.yml

stages:
  - .pre
  - build
  - linters
  - test

.common:
  tags: [bb5]
  script: ci/bb5-pr.sh
  variables:
    # Just run everything in the same, persistent, directory.
    bb5_build_dir: pipeline

setup virtualenv:
  extends: .common
  stage: .pre
  before_script:
    - export

trigger cvf:
  stage: .pre
  variables:
    # Tell the CVF pipeline to use the current ref of NMODL, this works because
    # the CVF CI uses the `gitlab-pipelines` helper components.
    SPACK_PACKAGE_REF_nmodl: "commit='${CI_COMMIT_SHA}'"
  rules:
    # Don't run on PRs targeting the LLVM development branch
    - if: '$CI_EXTERNAL_PULL_REQUEST_TARGET_BRANCH_NAME == "llvm"'
      when: never
    # Otherwise always run this
    - when: always
  trigger:
    project: hpc/cvf
    # Make the NMODL CI status depend on the CVF CI status
    strategy: depend

build intel:
  needs: ["setup virtualenv"]
  extends: .common
  stage: build
  variables:
    # We cloned in .pre
    GIT_STRATEGY: none

test intel:
  needs: ["build intel"]
  extends: .common
  stage: test
  variables:
    # We cloned in .pre
    GIT_STRATEGY: none

build pgi:
  needs: ["setup virtualenv"]
  extends: .common
  stage: build
  variables:
    # We cloned in .pre
    GIT_STRATEGY: none
    bb5_constraint: volta

test pgi:
  needs: ["build pgi"]
  extends: .common
  stage: test
  variables:
    # We cloned in .pre
    GIT_STRATEGY: none

cmake format:
  extends: .common
  stage: linters
  needs: ["build intel"]
  variables:
    # We cloned in .pre
    GIT_STRATEGY: none

clang format:
  extends: .common
  stage: linters
  needs: ["build intel"]
  variables:
    # We cloned in .pre
    GIT_STRATEGY: none
