include:
  - project: hpc/gitlab-pipelines
    file: github-project-pipelines.gitlab-ci.yml
  - project: hpc/gitlab-upload-logs
    file: enable-upload.yml

stages:
  - .pre
  - build
  - linters
  - test

.common:
  tags: [bb5]
  script: ci/bb5-pr.sh
  variables:
    # Just run everything in the same, persistent, directory.
    bb5_build_dir: pipeline

setup virtualenv:
  extends: .common
  stage: .pre
  before_script:
    - export
  variables:
    # This might pull in more than needed, but it should be enough to allow the
    # two build jobs to run in parallel safely. Otherwise they will race each
    # other to lazily update the submodules during the CMake phase, which can
    # cause errors.
    GIT_SUBMODULE_STRATEGY: recursive

build intel:
  needs: ["setup virtualenv"]
  extends: .common
  stage: build
  variables:
    # We cloned in .pre
    GIT_STRATEGY: none

test intel:
  needs: ["build intel"]
  extends: .common
  stage: test
  variables:
    # We cloned in .pre
    GIT_STRATEGY: none

build pgi:
  needs: ["setup virtualenv"]
  extends: .common
  stage: build
  variables:
    # We cloned in .pre
    GIT_STRATEGY: none
    bb5_constraint: volta

test pgi:
  needs: ["build pgi"]
  extends: .common
  stage: test
  variables:
    # We cloned in .pre
    GIT_STRATEGY: none

cmake format:
  extends: .common
  stage: linters
  needs: ["build intel"]
  variables:
    # We cloned in .pre
    GIT_STRATEGY: none

clang format:
  extends: .common
  stage: linters
  needs: ["build intel"]
  variables:
    # We cloned in .pre
    GIT_STRATEGY: none
