include:
  - project: hpc/gitlab-pipelines
    file:
      - spack-build-components.gitlab-ci.yml
      - github-project-pipelines.gitlab-ci.yml
  - project: hpc/gitlab-upload-logs
    file: enable-upload.yml

trigger cvf:
  stage: .pre
  rules:
    # Don't run on PRs targeting the LLVM development branch
    - if: '$CI_EXTERNAL_PULL_REQUEST_TARGET_BRANCH_NAME == "llvm"'
      when: never
    # Otherwise always run this
    - when: always
  trigger:
    project: hpc/cvf
    # Make the NMODL CI status depend on the CVF CI status
    strategy: depend
  variables:
    # Tell CVF to use the same commits/branches as NMODL.
    SPACK_ENV_FILE_URL: $SPACK_SETUP_COMMIT_MAPPING_URL

.spack_nmodl:
  variables:
    SPACK_PACKAGE: nmodl
    SPACK_PACKAGE_SPEC: ~legacy-unit+python
    SPACK_EXTRA_MODULES: llvm
    SPACK_INSTALL_EXTRA_FLAGS: -v

spack_setup:
  extends: .spack_setup_ccache
  variables:
    NMODL_COMMIT: ${CI_COMMIT_SHA}
    # Enable fetching GitHub PR descriptions and parsing them to find out what
    # branches to build of other projects.
    PARSE_GITHUB_PR_DESCRIPTIONS: "true"

build:intel:
  extends:
    - .spack_build
    - .spack_nmodl
  variables:
    SPACK_PACKAGE_COMPILER: intel

build:gcc:
  extends:
    - .spack_build
    - .spack_nmodl
  variables:
    SPACK_PACKAGE_COMPILER: gcc
    SPACK_PACKAGE_DEPENDENCIES: ^bison%gcc^flex%gcc^py-jinja2%gcc^py-sympy%gcc^py-pyyaml%gcc

.nmodl_tests:
  variables:
    # https://github.com/BlueBrain/nmodl/issues/737
    bb5_ntasks: 1

test:intel:
  extends:
    - .ctest
    - .nmodl_tests
  needs: ["build:intel"]

test:gcc:
  extends:
    - .ctest
    - .nmodl_tests
  needs: ["build:gcc"]
