#=============================================================================
# Azure Pipeline NMODL settings
#=============================================================================
jobs:
- job: 'ubuntu1604'
  pool:
    vmImage: 'ubuntu-16.04'
  displayName: 'Ubuntu (16.04), GCC 8.1'
  steps:
  - checkout: self
    submodules: true
  - script: |
      sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
      sudo apt-add-repository -y ppa:deadsnakes/ppa
      sudo apt update
      sudo apt install -y g++-8 flex bison cmake
      sudo apt-get install -y python3.7 python3.7-dev
      python3.7 -m pip install -U pip setuptools
      python3.7 -m pip install --user 'Jinja2>=2.9.3' 'PyYAML>=3.13' pytest 'sympy>=1.3'
    displayName: 'Install Depdendencies'
  - script: |
      export PATH=/home/vsts/.local/bin:$PATH
      export CXX='g++-8'
      mkdir -p $(Build.Repository.LocalPath)/build
      cd $(Build.Repository.LocalPath)/build
      cmake .. -DPYTHON_EXECUTABLE=`which python3.7` -DCMAKE_INSTALL_PREFIX=$HOME/nmodl
      make -j 2
      make test
    displayName: 'Build and Run Tests'
- job: 'osx1014'
  pool:
    vmImage: 'macOS-10.14'
  displayName: 'MacOS (10.14), AppleClang 10.0'
  steps:
  - checkout: self
    submodules: true
  - script: |
      brew install flex bison cmake python@3
      python3 -m pip install -U pip setuptools
      python3 -m pip install --user 'Jinja2>=2.9.3' 'PyYAML>=3.13' pytest 'sympy>=1.3'
    displayName: 'Install Depdendencies'
  - script: |
      export PATH=/usr/local/opt/flex/bin:/usr/local/opt/bison/bin:$PATH;
      mkdir -p $(Build.Repository.LocalPath)/build
      cd $(Build.Repository.LocalPath)/build
      cmake .. -DPYTHON_EXECUTABLE=`which python3` -DCMAKE_INSTALL_PREFIX=$HOME/nmodl
      make -j 2
      make test
    displayName: 'Build and Run Tests'

