[project]
name = "NMODL"
authors = [
    {name = "Blue Brain Project", email = "bbp-ou-hpc@groupes.epfl.ch"},
]
description = "NEURON Modeling Language Source-to-Source Compiler Framework"
license = {file = "LICENSE"}
readme = {file = "README.rst", content-type = "text/x-rst"}
dynamic = ["version"]
dependencies = [
    "find_libpython",
    "sympy>=1.3",
    "Jinja2>=2.9.3",
    "PyYAML>=3.13",
]

[build-system]
requires = [
    "setuptools",
    "find_libpython",
    "scikit-build",
    "sympy>=1.3",
    "Jinja2>=2.9.3",
    "PyYAML>=3.13",
    "setuptools-scm>=8.0",
]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
