[project]
name = "NMODL"
authors = [
    {name = "Blue Brain Project", email = "bbp-ou-hpc@groupes.epfl.ch"},
]
description = "NEURON Modeling Language Source-to-Source Compiler Framework"
license = {file = "LICENSE"}
readme = {file = "README.rst", content-type = "text/x-rst"}
dynamic = ["version"]
dependencies = [
    "find_libpython",
    "sympy>=1.3",
    "Jinja2>=2.9.3",
    "PyYAML>=3.13",
]

[build-system]
requires = [
    "scikit-build-core",
    "setuptools-scm>=8.0",
    "find_libpython",
    "sympy>=1.3",
    "Jinja2>=2.9.3",
    "PyYAML>=3.13",
]
build-backend = "scikit_build_core.build"

[tool.scikit-build]
cmake.verbose = true
metadata.version.provider = "scikit_build_core.metadata.setuptools_scm"
wheel.packages = ["nmodl"]

[tool.scikit-build.cmake.define]
LINK_AGAINST_PYTHON = "FALSE"
NMODL_ENABLE_TESTS = "FALSE"

[tool.setuptools_scm]
