# NOTE this file serves one purpose: to silence Circle CI.
# Delete at will.
#
# Copied&modified from: https://circleci.com/docs/sample-config/
version: 2.1

# Define the jobs we want to run for this project
jobs:
  build:
    docker:
      - image: cimg/base:2023.03
    steps:
      - run: echo "this is the build job"

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build
