/*
 * Copyright 2023 Blue Brain Project, EPFL.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#pragma once

#include <string>

#include "parser/diffeq_context.hpp"


namespace nmodl {
namespace parser {

/// flex generated scanner class (extends base lexer class of flex)
class DiffeqlLexer;

/// parser class generated by bison
class DiffeqParser;

/**
 * @addtogroup parser
 * @{
 */

/**
 * \class DiffeqDriver
 * \brief Class that binds all pieces together for parsing differential equations
 *
 * Driver class bind components required for lexing, parsing and ast
 * generation for differential equations.
 */
class DiffeqDriver {
  private:
    static std::string solve_equation(std::string& state,
                                      int order,
                                      std::string& rhs,
                                      std::string& method,
                                      bool& cnexp_possible,
                                      bool debug = false);

    /// parse given equation into lhs, rhs and find it's order and state variable
    static void parse_equation(const std::string& equation,
                               std::string& state,
                               std::string& rhs,
                               int& order);

  public:
    DiffeqDriver() = default;

    /// solve equation using provided method
    static std::string solve(const std::string& equation, std::string method, bool debug = false);

    /// check if given equation can be solved using cnexp method
    static bool cnexp_possible(const std::string& equation, std::string& solution);
};

/** @} */  // end of parser

}  // namespace parser
}  // namespace nmodl
