/*************************************************************************
 * Copyright (C) 2018-2019 Blue Brain Project
 *
 * This file is part of NMODL distributed under the terms of the GNU
 * Lesser General Public License. See top-level LICENSE file for details.
 *************************************************************************/

#pragma once

#include "units/units.hpp"
#include <algorithm>
#include <map>
#include <memory>
#include <string>
#include <vector>

namespace nmodl {
namespace parser {

/// flex generated scanner class (extends base lexer class of flex)
class UnitLexer;

/// parser class generated by bison
class UnitParser;

class location;

/**
 * \class UnitDriver
 * \brief Class that binds all pieces together for parsing C verbatim blocks
 */
class UnitDriver {
  private:
    /// all tokens encountered
    std::vector<std::string> tokens;

    /// enable debug output in the flex scanner
    bool trace_scanner = false;

    /// enable debug output in the bison parser
    bool trace_parser = false;

    /// pointer to the lexer instance being used
    UnitLexer* lexer = nullptr;

    /// pointer to the parser instance being used
    UnitParser* parser = nullptr;

    /// print messages from lexer/parser
    bool verbose = false;

  public:
    std::shared_ptr<nmodl::units::UnitTable> Table = nullptr;
    /// file or input stream name (used by scanner for position), see todo
    std::string streamname;

    UnitDriver() = default;
    UnitDriver(bool strace, bool ptrace);

    void error(const std::string& m);

    bool parse_stream(std::istream& in);
    bool parse_string(const std::string& input);
    bool parse_file(const std::string& filename);
    void scan_string(std::string& text);
    void add_token(const std::string&);

    void error(const std::string& m, const location& l);

    void set_verbose(bool b) {
        verbose = b;
    }

    bool is_verbose() const {
        return verbose;
    }

    std::vector<std::string> all_tokens() const {
        return tokens;
    }

    void print_tokens() {
        for (auto it: tokens) {
            std::cout << it << std::endl;
        }
    }

    bool has_token(std::string token) {
        if (std::find(tokens.begin(), tokens.end(), token) != tokens.end()) {
            return true;
        }
        return false;
    }
};

}  // namespace parser
}  // namespace nmodl
