/*************************************************************************
 * Copyright (C) 2018-2019 Blue Brain Project
 *
 * This file is part of NMODL distributed under the terms of the GNU
 * Lesser General Public License. See top-level LICENSE file for details.
 *************************************************************************/

#pragma once

/**
 * \file
 * \brief \copybrief nmodl::visitor::GlobalToRangeVisitor
 */

#include <sstream>
#include <string>
#include <vector>

#include "ast/ast.hpp"
#include "visitors/ast_visitor.hpp"
#include "visitors/visitor_utils.hpp"

namespace nmodl {
namespace visitor {

/**
 * @addtogroup visitor_classes
 * @{
 */

/**
 * \class GlobalToRangeVisitor
 * \brief Visitor for Units blocks of AST
 *
 * This is simple example of visitor that uses base AstVisitor
 * interface. We override AstVisitor::visit_program, AstVisitor::visit_unit_def
 * and AstVisitor::visit_factor_def method. Furthermore it keeps the
 * parser::UnitDriver to parse the units file and the strings generated by the
 * units in the mod files.
 */

class GlobalToRangeVisitor: public AstVisitor {
  private:
    /// ast::Ast* node
    ast::Ast* ast;

  public:
    /// \name Ctor & dtor
    /// \{

    /// Default UnitsVisitor constructor
    GlobalToRangeVisitor() = default;

    /// Constructor that takes as parameter the AST
    explicit GlobalToRangeVisitor(ast::Ast* node)
        : ast(node) {}

    /// \}

    /// Function to visit all the ast::UnitDef nodes and parse the units defined as
    /// ast::UnitDef in the UNITS block of mod files
    void visit_global_var(ast::GlobalVar* node) override;
    void visit_range_var(ast::RangeVar* node) override;
    void visit_neuron_block(ast::NeuronBlock* node) override;
};

/** @} */  // end of visitor_classes

}  // namespace visitor
}  // namespace nmodl
