version: '3.7'
services:
  notebook:
    image: nmodl:latest
    build: recipe
    hostname: ${HOSTNAME}
    ports:
    - "8888:8888"
    environment:
    - USER_LOGIN=${USER}
    - USER_ID=${DUID}
    - GROUP_ID=${DGID}
    volumes:
    - $PWD/notebooks:/nmodl/notebooks/my_notebooks
    command:
    - jupyter
    - notebook
    - --notebook-dir=/nmodl/notebooks
    - --ip=0.0.0.0
    - --no-browser
    - --allow-root
