name: clang-cmake-format-check

concurrency:
  group: ${{ github.workflow }}#${{ github.ref }}
  cancel-in-progress: true

on:
    push:

jobs:
  build:
    name: clang-cmake-format-check
    runs-on: ubuntu-20.04
    steps:
        - name: Fetch repository
          uses: actions/checkout@v2
        - name: Install clang-format 11
          run: |
              sudo apt-get update
              sudo apt-get install clang-format-11 ninja-build python3-pip python3-dev flex libfl-dev bison
        - name: Install cmake-format 0.6.13
          run:  python3 -m pip install cmake-format==0.6.13
        - name: Install Python3 dependencies
          run: |
            pip3 install -U pip setuptools scikit-build Jinja2 PyYAML pytest \
              'sympy>=1.3,<1.9' 'cmake-format==0.6.13'
        - name: Configure
          shell: bash
          working-directory: ${{runner.workspace}}/nmodl
          run: |
              export PATH=/home/runner/.local/bin:$PATH
              mkdir BUILD && cd BUILD
              cmake -DNMODL_ENABLE_PYTHON_BINDINGS=OFF -DNMODL_CLANG_FORMAT=ON -DNMODL_CMAKE_FORMAT=ON -DClangFormat_EXECUTABLE=$(which clang-format-11) -DCMakeFormat_EXECUTABLE=$(which cmake-format) ..
        - name: Run clang-format
          shell: bash
          working-directory: ${{runner.workspace}}/nmodl/BUILD
          run: cmake --build . --target check-clang-format
        - name: Run cmake-format
          shell: bash
          working-directory: ${{runner.workspace}}/nmodl/BUILD
          run: cmake --build . --target check-cmake-format

