name: Build wheels

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]

    steps:
      - name: Setup Flex and Bison
        if: runner.os == 'Windows'
        run: |
          choco install winflexbison3 -y

      - name: Setup Flex and Bison
        if: runner.os == 'macOS'
        run: |
          brew install flex bison

      # for multi-arch builds
      - name: Set up QEMU
        if: runner.os == 'Linux'
        uses: docker/setup-qemu-action@v3
        with:
          platforms: all

      - uses: actions/checkout@v4

      # Used to host cibuildwheel
      - uses: actions/setup-python@v3

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.16.5

      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse
        # to supply options, put them in 'env', like:
        env:
          # we skip PyPy, 32-bit builds, and musllinux builds
          CIBW_SKIP: "pp* *-win32 *-manylinux_i686 *-musllinux_i686 *-musllinux_x86_64"
          CIBW_BUILD: "cp311-win_amd64"
          # MacOS-specific setup
          CIBW_ENVIRONMENT_MACOS: >
            PATH="/opt/homebrew/opt/flex/bin:/opt/homebrew/opt/bison/bin:/usr/local/opt/flex/bin:/usr/local/opt/bison/bin:$PATH"
            MACOSX_DEPLOYMENT_TARGET='10.15'
          CIBW_CONFIG_SETTINGS_MACOS: "build-dir=_build"
          # Linux-specific setup
          CIBW_ENVIRONMENT_LINUX: >
            PATH=/nmodlwheel/flex/bin:/nmodlwheel/bison/bin:$PATH
          # TODO: replace this with a custom Docker image to speed-up builds
          CIBW_BEFORE_BUILD_LINUX: bash packaging/install_dependencies.sh

      - uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: ./wheelhouse/*.whl
